### ISSUE TITLE
Should we archive this repo?

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies-blog#4]
@econchick @estherbester @lorenanicole @Mariatta @pyladies/core This repo doesn't seem to still be active. Should we archive it in GitHub?

**Comment by Mariatta** [comment]
If this is not used at all, then I'm good with archiving it to avoid confusion. Thanks,

**Comment by willingc** [comment]
@econchick Do you think we can go ahead and archive this repo?

**Comment by lorenanicole** [comment]
Update: @econchick we will be archiving this repo in 7 days on August 5 2019. If there are other repos that should be archived, please let us know! @willingc is running lead on this! Thanks 🙇‍♀ !

**Comment by willingc** [comment]
Archiving this repo today.
